name: cross platform ci

# 1
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
      - 'deps-lock.json'
      - 'resources/CLOJURE_LSP_VERSION'
      - 'docs/**'
      - 'images/**'
      - 'mkdocs.yml'
      - '.github/workflows/bump_deps.yml'
      - '.github/workflows/bump_downstreams.yml'
      - '.github/workflows/nightly.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/release.yml'

  pull_request:

jobs:
  cross-platform:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        #os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      # - name: Install Clojure
      #   if: ${{ matrix.os != 'windows-latest' }}
      #   uses: ikappaki/setup-clojure@issue/pwsh
      #   with:
      #     cli: 1.10.3.1013
      #     lein: 2.9.1
      #     bb: 0.8.157
      #     boot: 2.8.3

      # boot is not yet available with this action, install separately.
      # see https://github.com/DeLaGuardo/setup-clojure/issues/57.
      - name: Install Clojure (MS-Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        # uses: DeLaGuardo/setup-clojure@master
        uses: ikappaki/setup-clojure@issue/pwsh
        with:
          cli: 1.10.3.1013
          lein: 2.9.1
          bb: 0.8.157
      # - name: Install boot on MS-Windows
      #   if: ${{ matrix.os == 'windows-latest' }}
      #   run: |
      #     $env:BOOT_BIN_DIR="$HOME\.boot\bin"

      #     if (!(Test-Path $env:BOOT_BIN_DIR)) {new-item "$env:BOOT_BIN_DIR" -ItemType directory}
      #     iwr -Uri https://github.com/boot-clj/boot-bin/releases/download/latest/boot.exe `
      #     -outfile $env:BOOT_BIN_DIR/boot.exe
      #     echo $env:BOOT_BIN_DIR | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      #     # workaround for finding the JDK
      #     reg add "HKLM\SOFTWARE\JavaSoft\Java Development Kit\1.8" /v JAVAHome /d "$env:JAVA_HOME" /f
      #     # bootstrap
      #     & "$env:BOOT_BIN_DIR/boot.exe" -V

      - name: Run cross platform tests
        shell: powershell
        run: |
          clojure --version
          # & pwsh -NoProfile -Command clojure --version
          # cd lib
          # clojure -M:test --focus clojure-lsp.classpath-test

      - name: Run cross platform tests pwsh
        run: |
          Get-Command
          clojure --version
          # cd lib
          # clojure -M:test --focus clojure-lsp.classpath-test
